apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-app-1
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/demo-app-1/deploy" # path inside Git repo to the Kustomize secretsGenerator (UNENCRYPTED kustomization.yaml)
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # the GitRepository source that holds your repo (match your existing source name)
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age # the name of the secret that hold the private encryption key

