apiVersion: v1
kind: Pod
metadata:
  name: demo-app-1
  namespace: default
  labels:
    app: flux-sops-demo
spec:
  restartPolicy: Never
  containers:
    - name: tester
      image: alpine:3.18
      command: ["sh", "-c", "echo pod started; sleep 3600"]
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-app-1-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-app-1-secrets
              key: password
