apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../pod.yaml

secretGenerator:
  - name: demo-app-1-secrets
    files:
      - username=./username.txt
      - password=./password.txt

generatorOptions:
  disableNameSuffixHash: true
